# Generated by Django 4.2.17 on 2024-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news_alter_buyer_balance_alter_game_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_for_postgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
    ]
